font_family JetBrainsMono Nerd Font Mono
font_size 12.0
window_padding_width 4
scrollback_indicator_opacity 0


# BEGIN_KITTY_THEME
# If you use Waybar, uncomment pywal include and comment the noctalia one
#include ~/.cache/wal/colors-kitty.conf
include current-theme.conf
# END_KITTY_THEME
