#!/bin/bash

WALL="$1"

if [ -z "$WALL" ]; then
    echo "Usage: wal-set /path/to/wallpaper"
    exit 1
fi

echo "Setting wallpaper: $WALL"

awww img "$WALL" --resize fit --transition-type grow

wal -i "$WALL"

c_active=$(sed -n '6p' ~/.cache/wal/colors | tr -d '\n')
c_inactive=$(sed -n '7p' ~/.cache/wal/colors | tr -d '\n')

sed -i "s/active-color \"[^\"]*\"/active-color \"$c_active\"/" ~/.config/niri/config.kdl
sed -i "s/inactive-color \"[^\"]*\"/inactive-color \"$c_inactive\"/" ~/.config/niri/config.kdl

pkill waybar && waybar &

