color0 #131318
color1 #ffb4ab
color2 #c2c1ff
color3 #c4c3ec
color4 #fface9
color5 #c2c1ff
color6 #c4c3ec
color7 #e4e1e9
color8 #918f9d
color9 #ffb4ab
color10 #c2c1ff
color11 #c4c3ec
color12 #fface9
color13 #c2c1ff
color14 #c4c3ec
color15 #e4e1e9

cursor                #e4e1e9
cursor_text_color     #131318
background            #131318
foreground            #e4e1e9
selection_foreground  #c7c5d3
selection_background  #464651
active_border_color   #c2c1ff
inactive_border_color #464651
url_color             #c2c1ff

active_tab_foreground   #25237b
active_tab_background   #c2c1ff
inactive_tab_foreground #c7c5d3
inactive_tab_background #464651
cursor_trail_color      #c7c5d3
